### ISSUE TITLE
Refactor package names to remove underscores

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/lime#27]
Java and scala package names don't usually contain underscores.

I'd propose

org.bdgenomics.lime.set_statistics &rarr; org.bdgenomics.lime.statistics
org.bdgenomics.lime.set_theory &rarr; org.bdgenomics.lime.theory

**Comment by devin-petersohn** [comment]
how about org.bdgenomics.lime.sets.statistics / org.bdgenomics.lime.sets.theory?

**Comment by heuermh** [comment]
Yeah I was thinking that too, but lime is already about sets, no?

**Comment by devin-petersohn** [comment]
That is true, but I don't like the `lime.theory` name. Maybe we could use `lime.arithmetic`. That might make it more clear.

**Comment by heuermh** [comment]
math, maths, operations, op?

**Comment by devin-petersohn** [comment]
op is good for me.

**Comment by heuermh** [comment]
> op is good for me.

Phew!  Naming stuff is always hard
